- .github/workflows/publish-packages.yaml
> fix(ci): 초기 tag 가 없는 경우에도 다음으로 넘어가도록 처리

- .github/workflows/publish-packages.yaml
> fix(ci): add PAT in publish

- .github/workflows/publish-packages.yaml
> fix(ci): publish 고치기

- packages/hello/package.json
> chore(hello): 배포 테스트

- .pnp.cjs
- .scripts/scaffold.sh
- packages/foo/package.json
- packages/foo/src/index.ts
- packages/foo/tsconfig.json
- yarn.lock
> test(foo): 패키지 배포 테스트

- _templates/package/new/package.json.ejs.t
- packages/foo/package.json
> fix(scaffolding): 스캐폴딩 수정

- packages/foo/package.json
> fix(foo): version 0.0.2

- .pnp.cjs
- packages/ui-desktop/.eslintrc.json
- packages/ui-desktop/README.md
- packages/ui-desktop/package.json
- packages/ui-desktop/src/Footer/Footer.tsx
- packages/ui-desktop/src/Footer/index.ts
- packages/ui-desktop/src/Header/Header.tsx
- packages/ui-desktop/src/Header/index.ts
- packages/ui-desktop/src/index.ts
- packages/ui-desktop/tsconfig.json
- yarn.lock
ui-dekstop 패키지 추가했어요
Header, Footer 는 되나 확인하려고 일단 넣어놓기만 했습니다
> feat(ui-desktop): ui-desktop 패키지 추가

- packages/ui-desktop/src/Button/Button.tsx
- packages/ui-desktop/src/Button/index.ts
- packages/ui-desktop/src/Tag/Tag.tsx
- packages/ui-desktop/src/Tag/index.ts
- packages/ui-desktop/src/Text/Text.tsx
- packages/ui-desktop/src/Text/index.ts
- packages/ui-desktop/src/Text/types.ts
- packages/ui-desktop/src/index.ts
제가 pongdang 님의 컴포넌트들을 이사시켰습니다! 🙏
> feat(ui-desktop): Button, Tag, Text 이사

- packages/ui-desktop/.storybook/main.js
> fix: staticDirs 수정

- packages/ui-desktop/.storybook/main.js
> docs(desktop-ui): 스토리북 docs 문서 추가

- .eslintrc.cjs
- tsconfig.base.json
- 나중에는 eslint 설정을 따로 라이브러리로 빼서 공통으로 쓰도록 하겠습니다.
> fix(eslint): 설정 동기화

- .eslintrc.cjs
- packages/ui-desktop/src/Button/Button.tsx
- packages/ui-desktop/src/Header/Header.stories.tsx
- packages/ui-desktop/src/Header/Header.tsx
- packages/ui-desktop/src/Header/compound/HeaderLogo.tsx
- packages/ui-desktop/src/Text/Text.tsx
- packages/ui-desktop/tsconfig.json
> fix: lint 룰 추가 react/jsx

- packages/ui-desktop/src/Tag/Tag.tsx
> fix(ui-desktop): Tag 컴포넌트에 children 타입 추가

- packages/ui-desktop/src/Header/Header.tsx
> fix(desktop-ui): Header 컴포넌트의 서버 컴포넌트 지원을 위해 useEffect 제거

- .github/workflows/publish-packages.yaml
> fix(ci): bump 푸시할 때는 no verify 추가

- packages/ui-desktop/src/Button/Button.tsx
- packages/ui-desktop/src/Footer/Footer.tsx
- packages/ui-desktop/src/Header/Header.tsx
- packages/ui-desktop/src/Header/compound/HeaderLogo.tsx
- packages/ui-desktop/src/Tag/Tag.tsx
- packages/ui-desktop/src/Text/Text.tsx
> fix(ui-desktop): 누락된 className prop 추가

- .github/workflows/publish-packages.yaml
- packages/ui-desktop/README.md
> ci: add logging for changed

- .github/workflows/publish-packages.yaml
> feat(ci): noti to slack

- .github/workflows/publish-packages.yaml
- packages/hello/README.md
> fix(ci): 배포 얼럿 고치기 5

- .github/workflows/publish-packages.yaml
- packages/hello/README.md
> fix(ci): 배포 얼럿 고치기 6

- .github/workflows/publish-packages.yaml
- packages/hello/README.md
> fix(ci): 배포 얼럿 고치기 7

- .github/workflows/publish-packages.yaml
- packages/hello/README.md
> fix(ci): 배포 얼럿 고치기 9

- .github/workflows/publish-packages.yaml
- packages/hello/README.md
> fix(ci): 배포 얼럿 고치기 10

- packages/ui-desktop/src/Tag/Tag.tsx
> fix(ui-desktop): Tag 컴포넌트에 className 타입 추가
